Update workflow

diff --git a/.github/workflows/lint-and-test.yaml b/.github/workflows/lint-and-test.yaml
--- a/.github/workflows/lint-and-test.yaml
+++ b/.github/workflows/lint-and-test.yaml
@@ -13,28 +13,33 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v3
 
-      - name: Install shellcheck
-        run: sudo apt install shellcheck
-      - name: Install devscripts
-        run: sudo apt install devscripts
+      - name: Install bats, bats-assert, and bats-support
+        run: sudo apt install bats bats-assert bats-support
+      - name: Run bats
+        run: bats ./exercises/**/*.bats
 
-      - name: Run shellcheck
-        run: shellcheck ./exercises/**/*.sh
-      - name: Run checkbashisms
-        # exit code 4 is success in checkbashisms
-        # exit code not equal 0 is failure in github actions
-        # change exit code to 0 when it's 4
-        run: |
-          set +e
-          checkbashisms ./exercises/**/*.sh
-          [ "$?" -eq "4" ] && exit 0
+      # - name: Install shellcheck
+      #   run: sudo apt install shellcheck
+      # - name: Install devscripts (includes checkbashisms)
+      #   run: sudo apt install devscripts
+
+      # - name: Run shellcheck
+      #   run: shellcheck ./exercises/**/*.sh
+      # - name: Run checkbashisms
+      #   # exit code 4 is success in checkbashisms
+      #   # exit code not equal 0 is failure in github actions
+      #   # change exit code to 0 when it's 4
+      #   run: |
+      #     set +e
+      #     checkbashisms ./exercises/**/*.sh
+      #     [ "$?" -eq "4" ] && exit 0
 
       # TODO: run bats without node
-      - name: Setup Node
-        uses: actions/setup-node@v3
-        with:
-          node-version: 18
-      - name: Install dependencies
-        run: npm ci
-      - name: Run tests
-        run: npm test
+      # - name: Setup Node
+      #   uses: actions/setup-node@v3
+      #   with:
+      #     node-version: 18
+      # - name: Install dependencies
+      #   run: npm ci
+      # - name: Run tests
+      #   run: npm test
